import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@skinmama/components/ui/accordion';

export function QuestionAnswerSection() {
  const FAQS_QUESTION = [
    {
      question: 'What does an AI Skin Analysis include and how accurate is it?',
      answer:
        "SkinMama's Skin Analysis detects 15 key skin concerns including spots, texture, dark circles, oiliness, acne, droopy lower eyelid, radiance, wrinkles, eye bags, moisture, redness, droopy upper eyelid, firmness, and pores with AI technology which is highly accurate and verified with a 95% test-retest reliability rate. Additionally, our AI Skin Analysis helps clients find their unique skin type and skin age. Contact us to learn more.",
    },
    {
      question:
        'What is the best skin analyzer for medical spas and aestheticians?',
      answer:
        "SkinMama's Skincare Pro is the best AI skin analysis service for medical spas, aestheticians, beauty clinics, and dermatologists, offering fast and accurate assessment. It can be integrated easily into your business.",
    },
    {
      question: 'What are the benefits of using AI Skin Analysis?',
      answer:
        'Our Skin Analyzer includes a scope of detailed skin report, where all the skin concerns will be displayed as scores. It provides fast, precise results, identifying skin types and issues instantly, making it a valuable tool for medical spas, aestheticians, and dermatology practices. Additionally, based on the analysis, the AI tech can offer personalized skincare routine recommendations tailored to address the specific needs from the customers.',
    },
    {
      question: 'What kind of skin analyzer is suitable for my business?',
      answer:
        "A Skin Analyzer is often a machine or software that can scan and analyze a user's face, identifying skin concerns, and finally, providing personalized skincare routine recommendations. Talk to our experts and we'll give you the best advice on how to best integrated it into your business.",
    },

    {
      question: 'What tools or systems are best for skin analysis?',
      answer:
        "SkinMama's Skincare Pro is ideal for medical spas, aestheticians, and dermatologists, offering fast and accurate assessments. It identifies skin concerns within seconds and generates detailed reports based on user's skin condition.",
    },
    {
      question: 'How long does skin analysis take and what is the process?',
      answer:
        "SkinMama's AI Skin Analyzer takes only seconds, scanning the face through live camera or photos and instantly generating a detailed skin report for personalized skincare recommendations.",
    },
    {
      question: 'How is AI used in dermatology and skincare analysis?',
      answer:
        "SkinMama's AI Skin Analyzer helps clients identify skin concerns through photos or a live camera. This technology enables users to gain more insight into their skin conditions. Contact us to learn more.",
    },
    {
      question:
        'How does AI Skin Analysis work to identify the skin type and age?',
      answer:
        "Utilizing advanced AI, our Skin Analyzer scans to identify concerns such as acne, dark circles, and fine lines. It determines skin types by analyzing the T-zone and U-zone of user's face, evaluating three dimensions: oiliness, dryness, and redness. Based on various skin conditions, it accurately assesses the user's skin age.",
    },
    {
      question: 'What are the 8 types of skin?',
      answer:
        'There are eight primary skin types, each with its unique characteristics: normal, sensitive, dry, oily, dry sensitive, oily sensitive, combination and combination sensitive. Identifying your specific skin type is the first step toward tailoring a proper skincare routine. ',
    },
    {
      question: 'What is a skin scanner?',
      answer:
        "A skin scanner is an innovative device designed to analyze the skin's condition through a deep face analysis online with AI and generate a comprehensive report tailored to the user's skin characteristics. ",
    },

    {
      question: 'What is the AI skin score?',
      answer:
        "The AI skin score, generated by the AI Skin Analyzer, serves as a comprehensive indicator of various skin conditions. It takes into account a range of factors analyzed by the skin technology, providing users with a detailed assessment of their skin's overall condition and appearance.",
    },
    {
      question: 'How to check skin analysis?',
      answer:
        "With our Skin Scanner online free, analyzing a user's skin involves three steps:Step 1: Activate the Skin Analysis service by turning on the cameras on mobile devices. Step 2: The AI Skin Analyzer detects the user's skin concerns and displays skin scores by analyzing the skin conditions. Step 3: The AI Skin Analysis solution generates a skin report to help users understand their skin.",
    },
    {
      question: 'How to check skin type online?',
      answer:
        'Leveraging AI technology for skin type analysis can revolutionize how businesses offer personalized skincare solutions. Here’s how our Skin Analysis tool can help: Steps to Check Skin Type Online Access the AI Skin Analysis Tool: Utilize our AI Skin Analysis solution, designed for seamless integration into your platform. Upload a Photo or Turn on Live Camera: Clients upload a clear image of their face or use the live camera feature for real-time analysis. AI Analysis: Our advanced AI algorithms analyze the photo, considering various skin attributes like oiliness, dryness, and sensitivity. Receive Results: The AI provides a detailed skin type report—oily, dry, combination, or normal. Tailored Recommendations: Based on the analysis, the AI suggests customized skincare products and routines.',
    },
    {
      question: 'How to make a skin type diagnosis without machines?',
      answer:
        "SkinMama's Skin Analyzer makes it possible to perform a skin type diagnosis without machines. This advanced technology uses AI to analyze, providing an accurate diagnosis of skin type and specific needs. Our face analyzer tool focused on a personalized skin analysis to provide recommendations for products, treatments and skin care routines. This solution not only eliminates the need for expensive equipment, but also offers convenience and accuracy, significantly improving the customer's skin care experience.",
    },
    {
      question: 'What is a facial skin scan?',
      answer:
        "A facial skin scan, often referred to as a skin analysis facial scan, is a non-invasive, touchless procedure that employs advanced camera technology and artificial intelligence (AI) to assess the condition of an individual's skin. This process is widely used in the skincare and beauty industries to provide detailed insights into various skin concerns and conditions.",
    },
  ];
  return (
    <div className="bg-gradient-to-b from-gray-100 to-white h-full flex items-center justify-center p-6">
      <div className="w-full max-w-3xl mx-auto rounded-xl shadow-md overflow-hidden">
        <div className="py-8 px-4 sm:px-8">
          <h2 className="text-2xl font-bold text-center text-gray-800 mb-8">
            Frequently Asked Questions
          </h2>

          <Accordion type="single" collapsible className="w-full">
            {FAQS_QUESTION.map((questions) => (
              <AccordionItem
                value={questions.question}
                className="border-b border-gray-200"
                key={questions.question}
              >
                <AccordionTrigger className="py-4 text-lg font-medium text-gray-700 hover:text-indigo-600 transition-colors">
                  {questions.question}
                </AccordionTrigger>
                <AccordionContent className="py-3 text-gray-600">
                  {questions.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </div>
  );
}
